version: "3.9"
services:
  llm:
    build: .
    command: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ../../llm4compiler:/workspace/llm4compiler