# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llmserving.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10llmserving.proto\x12\nllmserving\" \n\x0ePredictRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"%\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\t2\xa5\x01\n\nLlmServing\x12\x44\n\x07Predict\x12\x1a.llmserving.PredictRequest\x1a\x1b.llmserving.PredictResponse\"\x00\x12Q\n\x12PredictStreamReply\x12\x1a.llmserving.PredictRequest\x1a\x1b.llmserving.PredictResponse\"\x00\x30\x01\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llmserving_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_PREDICTREQUEST']._serialized_start=32
  _globals['_PREDICTREQUEST']._serialized_end=64
  _globals['_PREDICTRESPONSE']._serialized_start=66
  _globals['_PREDICTRESPONSE']._serialized_end=103
  _globals['_LLMSERVING']._serialized_start=106
  _globals['_LLMSERVING']._serialized_end=271
# @@protoc_insertion_point(module_scope)
